import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

/**
 * POST /api/admin/seed-content
 * Seeds the database with default Blue Dreams Resort content.
 * Only creates records if the table is empty for that locale.
 */
export async function POST(req: Request) {
  try {
    const results: string[] = []

    // ==========================
    // 1. ROOMS
    // ==========================
    const existingRooms = await prisma.room.count({ where: { locale: 'tr' } })
    if (existingRooms === 0) {
      const roomsTr = [
        {
          locale: 'tr',
          slug: 'club',
          title: 'Club Oda',
          subtitle: 'Club Odalar',
          description: 'Konforlu ve şık tasarımı ile tatil keyfinizi artıran Club odalarımız, tüm ihtiyaçlarınızı karşılayacak modern donanıma sahiptir.',
          longDescription: 'Club odalarımız, ferah iç mekanları ve zarif dekorasyonları ile konuklarına rahat bir konaklama deneyimi sunar. Odalarımız klima, minibar, LCD TV, saç kurutma makinesi ve ücretsiz Wi-Fi gibi olanaklarla donatılmıştır. Balkonunuzdan havuz veya bahçe manzarasının tadını çıkarabilirsiniz.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/CLUB-ROOM-1.jpg',
          gallery: JSON.stringify([
            'https://bluedreamsresort.com/wp-content/uploads/2023/03/CLUB-ROOM-1.jpg',
            'https://bluedreamsresort.com/wp-content/uploads/2023/03/CLUB-ROOM-2.jpg',
          ]),
          size: '25 m²',
          view: 'Havuz / Bahçe',
          capacity: '2+1',
          amenities: JSON.stringify([
            { icon: 'Wifi', label: 'Ücretsiz Wi-Fi' },
            { icon: 'Wind', label: 'Klima' },
            { icon: 'Tv', label: 'LCD TV' },
            { icon: 'Bath', label: 'Duş / Banyo' },
          ]),
          features: JSON.stringify(['Klima', 'Wi-Fi', 'LCD TV', 'Minibar', 'Saç Kurutma Makinesi', 'Telefon', 'Elektronik Kasa']),
          whyChoose: 'Uygun fiyata konforlu bir tatil arayanlar için ideal.',
          order: 1,
        },
        {
          locale: 'tr',
          slug: 'deluxe',
          title: 'Deluxe Oda',
          subtitle: 'Deluxe Odalar',
          description: 'Geniş yaşam alanı ve üstün konfor sunan Deluxe odalarımız, deniz veya havuz manzaralı balkonları ile unutulmaz bir tatil vaat eder.',
          longDescription: 'Deluxe odalarımız, daha geniş yaşam alanları ve premium döşemeleriyle ayrıcalıklı bir konaklama sunar. Modern banyoları, şık mobilyaları ve özel balkonlarıyla misafirlerimize lüks bir deneyim yaşatır.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/DELUXE-ROOM-1.jpg',
          gallery: JSON.stringify([
            'https://bluedreamsresort.com/wp-content/uploads/2023/03/DELUXE-ROOM-1.jpg',
            'https://bluedreamsresort.com/wp-content/uploads/2023/03/DELUXE-ROOM-2.jpg',
          ]),
          size: '30 m²',
          view: 'Deniz / Havuz',
          capacity: '2+1',
          amenities: JSON.stringify([
            { icon: 'Wifi', label: 'Ücretsiz Wi-Fi' },
            { icon: 'Wind', label: 'Klima' },
            { icon: 'Tv', label: 'LCD TV' },
            { icon: 'Bath', label: 'Küvet + Duş' },
          ]),
          features: JSON.stringify(['Klima', 'Wi-Fi', 'LCD TV', 'Minibar', 'Saç Kurutma Makinesi', 'Telefon', 'Elektronik Kasa', 'Bornoz & Terlik']),
          whyChoose: 'Deniz manzarası ve geniş alan isteyenler için mükemmel.',
          order: 2,
        },
        {
          locale: 'tr',
          slug: 'family',
          title: 'Aile Odası',
          subtitle: 'Aile Odaları',
          description: 'Aileler için özel olarak tasarlanan odalarımız, geniş alanları ve çocuk dostu olanakları ile tüm ailenin konforunu düşünür.',
          longDescription: 'Aile odalarımız, birbirine bağlantılı veya geniş tek mekan olarak düzenlenerek tüm aile bireyleri için rahat bir konaklama alanı sunar. Çocuklar için özel donanımlar talep edilebilir.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/FAMILY-ROOM-1.jpg',
          gallery: JSON.stringify([
            'https://bluedreamsresort.com/wp-content/uploads/2023/03/FAMILY-ROOM-1.jpg',
          ]),
          size: '40 m²',
          view: 'Bahçe / Havuz',
          capacity: '2+2',
          amenities: JSON.stringify([
            { icon: 'Wifi', label: 'Ücretsiz Wi-Fi' },
            { icon: 'Wind', label: 'Klima' },
            { icon: 'Tv', label: 'LCD TV' },
            { icon: 'Bath', label: 'Banyo' },
          ]),
          features: JSON.stringify(['Klima', 'Wi-Fi', 'LCD TV', 'Minibar', 'Saç Kurutma Makinesi', 'Bağlantılı Oda İmkanı', 'Çocuk Yatağı']),
          whyChoose: 'Çocuklu aileler için geniş ve konforlu.',
          order: 3,
        },
        {
          locale: 'tr',
          slug: 'suite',
          title: 'Suite',
          subtitle: 'Suite Odalar',
          description: 'Ayrıcalıklı konuklarımız için tasarlanan Suite odalarımız, geniş yaşam alanı, özel jakuzi ve panoramik manzara ile benzersiz bir deneyim sunar.',
          longDescription: 'Suite odalarımız, ayrı oturma alanı, lüks banyo, jakuzi ve özel teras gibi üstün olanaklarla donatılmıştır. Bodrum\'un eşsiz manzarasına hakim konumu ile misafirlerine ayrıcalıklı bir tatil sunar.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/SUITE-1.jpg',
          gallery: JSON.stringify([
            'https://bluedreamsresort.com/wp-content/uploads/2023/03/SUITE-1.jpg',
            'https://bluedreamsresort.com/wp-content/uploads/2023/03/SUITE-2.jpg',
          ]),
          size: '55 m²',
          view: 'Deniz Manzarası',
          capacity: '2+1',
          amenities: JSON.stringify([
            { icon: 'Wifi', label: 'Ücretsiz Wi-Fi' },
            { icon: 'Wind', label: 'Klima' },
            { icon: 'Tv', label: 'LCD TV' },
            { icon: 'Bath', label: 'Jakuzi + Duş' },
          ]),
          features: JSON.stringify(['Klima', 'Wi-Fi', 'LCD TV', 'Minibar', 'Jakuzi', 'Ayrı Oturma Alanı', 'Özel Teras', 'Bornoz & Terlik', 'Espresso Makinesi']),
          whyChoose: 'Lüks ve ayrıcalık arayanlar için en iyi seçim.',
          order: 4,
        },
      ]

      const roomsEn = [
        {
          locale: 'en',
          slug: 'club',
          title: 'Club Room',
          subtitle: 'Club Rooms',
          description: 'Our Club rooms, with their comfortable and stylish design, are equipped with modern amenities to meet all your needs.',
          longDescription: 'Our Club rooms offer guests a comfortable stay with spacious interiors and elegant decorations. Rooms are equipped with air conditioning, minibar, LCD TV, hair dryer, and free Wi-Fi.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/CLUB-ROOM-1.jpg',
          size: '25 m²',
          view: 'Pool / Garden',
          capacity: '2+1',
          features: JSON.stringify(['Air Conditioning', 'Wi-Fi', 'LCD TV', 'Minibar', 'Hair Dryer', 'Telephone', 'Safe']),
          whyChoose: 'Ideal for those looking for a comfortable holiday at a great price.',
          order: 1,
        },
        {
          locale: 'en',
          slug: 'deluxe',
          title: 'Deluxe Room',
          subtitle: 'Deluxe Rooms',
          description: 'Our Deluxe rooms offer spacious living areas and premium comfort with sea or pool view balconies for an unforgettable holiday.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/DELUXE-ROOM-1.jpg',
          size: '30 m²',
          view: 'Sea / Pool',
          capacity: '2+1',
          features: JSON.stringify(['Air Conditioning', 'Wi-Fi', 'LCD TV', 'Minibar', 'Hair Dryer', 'Telephone', 'Safe', 'Bathrobe & Slippers']),
          whyChoose: 'Perfect for those who want a sea view and spacious room.',
          order: 2,
        },
        {
          locale: 'en',
          slug: 'family',
          title: 'Family Room',
          subtitle: 'Family Rooms',
          description: 'Specially designed for families, our rooms offer spacious areas and child-friendly amenities, ensuring comfort for the whole family.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/FAMILY-ROOM-1.jpg',
          size: '40 m²',
          view: 'Garden / Pool',
          capacity: '2+2',
          features: JSON.stringify(['Air Conditioning', 'Wi-Fi', 'LCD TV', 'Minibar', 'Hair Dryer', 'Connecting Room Option', 'Baby Cot']),
          whyChoose: 'Spacious and comfortable for families with children.',
          order: 3,
        },
        {
          locale: 'en',
          slug: 'suite',
          title: 'Suite',
          subtitle: 'Suite Rooms',
          description: 'Our Suite rooms, designed for distinguished guests, offer a unique experience with spacious living area, private jacuzzi and panoramic views.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/SUITE-1.jpg',
          size: '55 m²',
          view: 'Sea View',
          capacity: '2+1',
          features: JSON.stringify(['Air Conditioning', 'Wi-Fi', 'LCD TV', 'Minibar', 'Jacuzzi', 'Separate Living Area', 'Private Terrace', 'Bathrobe & Slippers', 'Espresso Machine']),
          whyChoose: 'The best choice for those seeking luxury and exclusivity.',
          order: 4,
        },
      ]

      await prisma.room.createMany({ data: [...roomsTr, ...roomsEn] })
      results.push(`✅ Rooms seeded: ${roomsTr.length + roomsEn.length} records (TR + EN)`)
    } else {
      results.push(`⏭️ Rooms: already have ${existingRooms} TR records, skipping`)
    }

    // ==========================
    // 2. DINING (Restaurants + Bars)
    // ==========================
    const existingDining = await prisma.dining.count({ where: { locale: 'tr' } })
    if (existingDining === 0) {
      const diningTr = [
        {
          locale: 'tr',
          title: 'Begonvılle Ana Restoran',
          type: 'Ana Restoran',
          description: 'Açık büfe kahvaltı, öğle ve akşam yemeklerinin sunulduğu ana restoranımız, Türk ve dünya mutfağından zengin lezzetler sunar. 450 kişi kapasiteli restoranımızda taze ve mevsimsel ürünlerle hazırlanan yemeklerin keyfini çıkarın.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/OPEN-BUFFET-1.jpg',
          cuisine: 'Türk & Dünya Mutfağı',
          hours: '07:00 – 10:00 / 12:30 – 14:00 / 19:00 – 21:30',
          capacity: '450',
          location: 'Ana Bina Zemin Kat',
          features: 'Açık Büfe, Canlı Mutfak, Çocuk Menüsü, Diyet Seçenekler, Teras',
          isActive: true,
          order: 1,
        },
        {
          locale: 'tr',
          title: 'Halicarnassus Balık Restoran',
          type: "A'la Carte",
          description: 'Ege\'nin taze deniz ürünlerini modern sunum anlayışıyla buluşturan à la carte restoranımız. Özenle seçilmiş şaraplar eşliğinde, deniz manzarasında eşsiz bir akşam yemeği deneyimi yaşayın.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/FISH-RESTAURANT-1.jpg',
          cuisine: 'Deniz Ürünleri',
          hours: '19:00 – 22:00',
          capacity: '80',
          location: 'Havuz Başı',
          features: 'À la Carte, Deniz Manzarası, Şarap Menüsü, Canlı Müzik',
          isActive: true,
          order: 2,
        },
        {
          locale: 'tr',
          title: 'La Locanda İtalyan Restoran',
          type: "A'la Carte",
          description: 'İtalya\'nın geleneksel lezzetlerini Ege\'nin büyüleyici atmosferinde sunan La Locanda. Ev yapımı makarnalar, taze pizzalar ve İtalyan tatlıları ile gerçek bir İtalyan deneyimi.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/ITALIAN-RESTAURANT-1.jpg',
          cuisine: 'İtalyan Mutfağı',
          hours: '19:00 – 22:00',
          capacity: '70',
          location: 'Bahçe İçi',
          features: 'À la Carte, Pizza Fırını, Ev Yapımı Makarna, Teras',
          isActive: true,
          order: 3,
        },
        {
          locale: 'tr',
          title: 'Far East Uzakdoğu Restoran',
          type: "A'la Carte",
          description: 'Uzakdoğu\'nun egzotik lezzetlerini keşfedin. Sushi, wok ve geleneksel Asya mutfağının en seçkin tatlarını modern bir sunum anlayışıyla deneyimleyin.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/FAR-EAST-1.jpg',
          cuisine: 'Uzakdoğu Mutfağı',
          hours: '19:00 – 22:00',
          capacity: '60',
          location: 'Havuz Üstü',
          features: 'À la Carte, Sushi Bar, Wok, Teppanyaki',
          isActive: true,
          order: 4,
        },
        {
          locale: 'tr',
          title: 'Snack Bar & Patisserie',
          type: "Snack",
          description: 'Gün boyu hafif atıştırmalıklar, taze sıkılmış meyve suları, dondurma ve pasta çeşitleri ile serinleyin.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/SNACK-BAR-1.jpg',
          cuisine: 'Snack & Patisserie',
          hours: '10:00 – 18:00',
          capacity: '50',
          location: 'Havuz Başı',
          features: 'Hamburger, Pide, Gözleme, Dondurma, Taze Meyve Suyu',
          isActive: true,
          order: 5,
        },
        // BARS
        {
          locale: 'tr',
          title: 'Lobby Lounge Bar',
          type: 'Bar',
          description: 'Lobi alanında yer alan Lounge Bar, çay ve kahve saatleri ile gün boyu içecek servisi sunar. Canlı müzik eşliğinde keyifli anlar yaşayın.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/LOBBY-BAR-1.jpg',
          cuisine: 'Kokteyl & İçecek',
          hours: '10:00 – 00:00',
          capacity: '100',
          location: 'Lobi',
          features: 'Canlı Müzik, Kokteyl, Çay Saati',
          isActive: true,
          order: 6,
        },
        {
          locale: 'tr',
          title: 'Havuz Barı',
          type: 'Bar',
          description: 'Havuz kenarında serinletici içecekler ve tropikal kokteyller sunan barımız. Yaz gününün tadını çıkarırken ferahlatıcı içeceklerinizin keyfini süren.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/POOL-BAR-1.jpg',
          cuisine: 'Kokteyl & Soğuk İçecek',
          hours: '10:00 – 18:00',
          capacity: '80',
          location: 'Ana Havuz',
          features: 'Tropikal Kokteyller, Frozen, Bira',
          isActive: true,
          order: 7,
        },
        {
          locale: 'tr',
          title: 'Plaj Barı',
          type: 'Bar',
          description: 'Özel plajımızda deniz kenarında kokteyllerin ve serinletici içeceklerin tadını çıkarın. Kumsal atmosferinde unutulmaz saatler geçirin.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/BEACH-BAR-1.jpg',
          cuisine: 'Kokteyl & İçecek',
          hours: '10:00 – 18:00',
          capacity: '60',
          location: 'Özel Plaj',
          features: 'Deniz Kenarı, Kokteyl, Şezlong Servisi',
          isActive: true,
          order: 8,
        },
        {
          locale: 'tr',
          title: 'Disco Bar',
          type: 'Bar',
          description: 'Geceleri DJ performansları ve canlı müzik ile eğlencenin merkezi. Dans pistitinde unutulmaz geceler yaşayın.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/DISCO-BAR-1.jpg',
          cuisine: 'Kokteyl & İçecek',
          hours: '23:00 – 02:00',
          capacity: '200',
          location: 'Eğlence Alanı',
          features: 'DJ, Canlı Müzik, Dans Pisti, Kokteyl',
          isActive: true,
          order: 9,
        },
      ]

      const diningEn = [
        {
          locale: 'en',
          title: 'Begonvılle Main Restaurant',
          type: 'Main Restaurant',
          description: 'Our main restaurant offers open buffet breakfast, lunch and dinner with a rich selection of Turkish and world cuisine. Enjoy fresh, seasonal dishes in our 450-person capacity restaurant.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/OPEN-BUFFET-1.jpg',
          cuisine: 'Turkish & International',
          hours: '07:00 – 10:00 / 12:30 – 14:00 / 19:00 – 21:30',
          capacity: '450',
          location: 'Main Building Ground Floor',
          features: 'Open Buffet, Live Cooking, Kids Menu, Diet Options, Terrace',
          isActive: true,
          order: 1,
        },
        {
          locale: 'en',
          title: 'Halicarnassus Fish Restaurant',
          type: "A'la Carte",
          description: 'An à la carte restaurant combining fresh Aegean seafood with modern presentation. Enjoy a unique dining experience with carefully selected wines and sea views.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/FISH-RESTAURANT-1.jpg',
          cuisine: 'Seafood',
          hours: '19:00 – 22:00',
          capacity: '80',
          location: 'Poolside',
          features: 'À la Carte, Sea View, Wine Menu, Live Music',
          isActive: true,
          order: 2,
        },
        {
          locale: 'en',
          title: 'La Locanda Italian Restaurant',
          type: "A'la Carte",
          description: 'La Locanda brings traditional Italian flavors to the enchanting Aegean atmosphere. Enjoy homemade pastas, fresh pizzas and Italian desserts for an authentic Italian experience.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/ITALIAN-RESTAURANT-1.jpg',
          cuisine: 'Italian',
          hours: '19:00 – 22:00',
          capacity: '70',
          location: 'Garden Area',
          features: 'À la Carte, Pizza Oven, Homemade Pasta, Terrace',
          isActive: true,
          order: 3,
        },
        {
          locale: 'en',
          title: 'Far East Asian Restaurant',
          type: "A'la Carte",
          description: 'Discover the exotic flavors of the Far East. Experience the finest tastes of sushi, wok and traditional Asian cuisine with modern presentation.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/FAR-EAST-1.jpg',
          cuisine: 'Asian Cuisine',
          hours: '19:00 – 22:00',
          capacity: '60',
          location: 'Above Pool',
          features: 'À la Carte, Sushi Bar, Wok, Teppanyaki',
          isActive: true,
          order: 4,
        },
        {
          locale: 'en',
          title: 'Snack Bar & Patisserie',
          type: "Snack",
          description: 'Enjoy light snacks, fresh squeezed juices, ice cream and pastries throughout the day.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/SNACK-BAR-1.jpg',
          cuisine: 'Snack & Patisserie',
          hours: '10:00 – 18:00',
          capacity: '50',
          location: 'Poolside',
          features: 'Burger, Pita, Pancake, Ice Cream, Fresh Juice',
          isActive: true,
          order: 5,
        },
        // BARS
        {
          locale: 'en',
          title: 'Lobby Lounge Bar',
          type: 'Bar',
          description: 'Located in the lobby area, the Lounge Bar serves beverages throughout the day with tea and coffee hours. Enjoy delightful moments with live music.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/LOBBY-BAR-1.jpg',
          cuisine: 'Cocktails & Beverages',
          hours: '10:00 – 00:00',
          capacity: '100',
          location: 'Lobby',
          features: 'Live Music, Cocktails, Tea Time',
          isActive: true,
          order: 6,
        },
        {
          locale: 'en',
          title: 'Pool Bar',
          type: 'Bar',
          description: 'Our poolside bar offers refreshing drinks and tropical cocktails. Enjoy cooling beverages while soaking up the summer sun.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/POOL-BAR-1.jpg',
          cuisine: 'Cocktails & Cold Drinks',
          hours: '10:00 – 18:00',
          capacity: '80',
          location: 'Main Pool',
          features: 'Tropical Cocktails, Frozen Drinks, Beer',
          isActive: true,
          order: 7,
        },
        {
          locale: 'en',
          title: 'Beach Bar',
          type: 'Bar',
          description: 'Enjoy cocktails and refreshing drinks by the sea on our private beach. Spend unforgettable hours in a seaside atmosphere.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/BEACH-BAR-1.jpg',
          cuisine: 'Cocktails & Beverages',
          hours: '10:00 – 18:00',
          capacity: '60',
          location: 'Private Beach',
          features: 'Beachfront, Cocktails, Sunbed Service',
          isActive: true,
          order: 8,
        },
        {
          locale: 'en',
          title: 'Disco Bar',
          type: 'Bar',
          description: 'The entertainment hub with DJ performances and live music at night. Enjoy unforgettable nights on the dance floor.',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2023/03/DISCO-BAR-1.jpg',
          cuisine: 'Cocktails & Beverages',
          hours: '23:00 – 02:00',
          capacity: '200',
          location: 'Entertainment Area',
          features: 'DJ, Live Music, Dance Floor, Cocktails',
          isActive: true,
          order: 9,
        },
      ]

      await prisma.dining.createMany({ data: [...diningTr, ...diningEn] })
      results.push(`✅ Dining seeded: ${diningTr.length + diningEn.length} records (TR + EN)`)

      // Seed Dining Events for the first restaurant
      const beg = await prisma.dining.findFirst({ where: { locale: 'tr', title: { contains: 'Begonvılle' } } })
      if (beg) {
        await prisma.diningEvent.createMany({
          data: [
            { diningId: beg.id, locale: 'tr', title: 'Türk Gecesi', description: 'Geleneksel Türk mutfağının en seçkin lezzetleri ile özel gece.', time: '19:00 – 22:00', isActive: true },
            { diningId: beg.id, locale: 'tr', title: 'Balık Gecesi', description: 'Taze Ege deniz ürünleri ile özel büfe.', time: '19:00 – 22:00', isActive: true },
            { diningId: beg.id, locale: 'tr', title: 'İtalyan Gecesi', description: 'İtalyan mutfağının klasikleri ile tematik akşam yemeği.', time: '19:00 – 22:00', isActive: true },
            { diningId: beg.id, locale: 'tr', title: 'Mangal Gecesi', description: 'Açık hava mangal partisi, canlı müzik eşliğinde.', time: '19:00 – 22:00', isActive: true },
          ]
        })
        results.push('✅ Dining events seeded: 4 records')
      }
    } else {
      results.push(`⏭️ Dining: already have ${existingDining} TR records, skipping`)
    }

    // ==========================
    // 3. MEETING ROOMS
    // ==========================
    const existingMeeting = await prisma.meetingRoom.count({ where: { locale: 'tr' } })
    if (existingMeeting === 0) {
      const meetingTr = [
        {
          locale: 'tr',
          title: 'Bodrum Salonu',
          description: 'Küçük toplantılar ve VIP görüşmeler için ideal, şık tasarımlı salon.',
          area: '50 m²',
          capacity: 'Tiyatro: 40 / Sınıf: 25 / U-Düzen: 20',
          capacityTheater: '40',
          capacityClass: '25',
          capacityBanquet: '20',
          height: '2.80 mt',
          type: 'Toplantı Odası',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2026/01/Bluedreamstanitimkiti_page-0019-1024x725.jpg',
          features: JSON.stringify(['Projeksiyon', 'Wi-Fi', 'Flipchart', 'Ses Sistemi']),
          order: 1,
        },
        {
          locale: 'tr',
          title: 'Ankara Salonu',
          description: 'Orta ölçekli toplantılar, seminerler ve workshop\'lar için uygun, tam donanımlı salon.',
          area: '120 m²',
          capacity: 'Tiyatro: 100 / Sınıf: 60 / U-Düzen: 40',
          capacityTheater: '100',
          capacityClass: '60',
          capacityBanquet: '40',
          height: '3.00 mt',
          type: 'Toplantı Salonu',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2026/01/Bluedreamstanitimkiti_page-0019-1024x725.jpg',
          features: JSON.stringify(['Projeksiyon', 'Wi-Fi', 'Ses Sistemi', 'Sahne', 'Kablosuz Mikrofon']),
          order: 2,
        },
        {
          locale: 'tr',
          title: 'İzmir Salonu',
          description: 'Seminerler ve küçük konferanslar için ideal, tüm teknik donanıma sahip salon.',
          area: '90 m²',
          capacity: 'Tiyatro: 80 / Sınıf: 45 / U-Düzen: 30',
          capacityTheater: '80',
          capacityClass: '45',
          capacityBanquet: '30',
          height: '2.90 mt',
          type: 'Toplantı Salonu',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2026/01/Bluedreamstanitimkiti_page-0019-1024x725.jpg',
          features: JSON.stringify(['Projeksiyon', 'Wi-Fi', 'Ses Sistemi', 'Flipchart']),
          order: 3,
        },
        {
          locale: 'tr',
          title: 'Antalya Salonu',
          description: 'Eğitim ve seminerler için düzenlenmiş, konforlu koltuklu salon.',
          area: '75 m²',
          capacity: 'Tiyatro: 60 / Sınıf: 35 / U-Düzen: 25',
          capacityTheater: '60',
          capacityClass: '35',
          capacityBanquet: '25',
          height: '2.80 mt',
          type: 'Toplantı Odası',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2026/01/Bluedreamstanitimkiti_page-0019-1024x725.jpg',
          features: JSON.stringify(['Projeksiyon', 'Wi-Fi', 'Kablosuz Mikrofon', 'Ses Sistemi']),
          order: 4,
        },
        {
          locale: 'tr',
          title: 'Board Room',
          description: 'Yönetim kurulu toplantıları için özel tasarlanmış VIP toplantı odası.',
          area: '40 m²',
          capacity: 'U-Düzen: 16',
          capacityTheater: '16',
          capacityClass: '12',
          capacityBanquet: '16',
          height: '2.80 mt',
          type: 'VIP Toplantı Odası',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2026/01/Bluedreamstanitimkiti_page-0019-1024x725.jpg',
          features: JSON.stringify(['LCD Ekran', 'Wi-Fi', 'Video Konferans', 'Minibar']),
          order: 5,
        },
      ]

      const meetingEn = [
        {
          locale: 'en',
          title: 'Bodrum Hall',
          description: 'Elegantly designed hall, ideal for small meetings and VIP gatherings.',
          area: '50 m²',
          capacity: 'Theater: 40 / Classroom: 25 / U-Shape: 20',
          capacityTheater: '40',
          capacityClass: '25',
          capacityBanquet: '20',
          height: '2.80 mt',
          type: 'Meeting Room',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2026/01/Bluedreamstanitimkiti_page-0019-1024x725.jpg',
          features: JSON.stringify(['Projector', 'Wi-Fi', 'Flipchart', 'Sound System']),
          order: 1,
        },
        {
          locale: 'en',
          title: 'Ankara Hall',
          description: 'Fully equipped hall suitable for medium-sized meetings, seminars and workshops.',
          area: '120 m²',
          capacity: 'Theater: 100 / Classroom: 60 / U-Shape: 40',
          capacityTheater: '100',
          capacityClass: '60',
          capacityBanquet: '40',
          height: '3.00 mt',
          type: 'Meeting Hall',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2026/01/Bluedreamstanitimkiti_page-0019-1024x725.jpg',
          features: JSON.stringify(['Projector', 'Wi-Fi', 'Sound System', 'Stage', 'Wireless Microphone']),
          order: 2,
        },
        {
          locale: 'en',
          title: 'Izmir Hall',
          description: 'Ideal for seminars and small conferences with full technical equipment.',
          area: '90 m²',
          capacity: 'Theater: 80 / Classroom: 45 / U-Shape: 30',
          capacityTheater: '80',
          capacityClass: '45',
          capacityBanquet: '30',
          height: '2.90 mt',
          type: 'Meeting Hall',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2026/01/Bluedreamstanitimkiti_page-0019-1024x725.jpg',
          features: JSON.stringify(['Projector', 'Wi-Fi', 'Sound System', 'Flipchart']),
          order: 3,
        },
        {
          locale: 'en',
          title: 'Antalya Hall',
          description: 'Comfortable hall arranged for training sessions and seminars.',
          area: '75 m²',
          capacity: 'Theater: 60 / Classroom: 35 / U-Shape: 25',
          capacityTheater: '60',
          capacityClass: '35',
          capacityBanquet: '25',
          height: '2.80 mt',
          type: 'Meeting Room',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2026/01/Bluedreamstanitimkiti_page-0019-1024x725.jpg',
          features: JSON.stringify(['Projector', 'Wi-Fi', 'Wireless Microphone', 'Sound System']),
          order: 4,
        },
        {
          locale: 'en',
          title: 'Board Room',
          description: 'VIP meeting room specially designed for board meetings.',
          area: '40 m²',
          capacity: 'U-Shape: 16',
          capacityTheater: '16',
          capacityClass: '12',
          capacityBanquet: '16',
          height: '2.80 mt',
          type: 'VIP Meeting Room',
          image: 'https://bluedreamsresort.com/wp-content/uploads/2026/01/Bluedreamstanitimkiti_page-0019-1024x725.jpg',
          features: JSON.stringify(['LCD Screen', 'Wi-Fi', 'Video Conference', 'Minibar']),
          order: 5,
        },
      ]

      await prisma.meetingRoom.createMany({ data: [...meetingTr, ...meetingEn] })
      results.push(`✅ Meeting rooms seeded: ${meetingTr.length + meetingEn.length} records (TR + EN)`)
    } else {
      results.push(`⏭️ Meeting rooms: already have ${existingMeeting} TR records, skipping`)
    }

    return NextResponse.json({ success: true, results })
  } catch (error: any) {
    console.error('[Seed Content] Error:', error)
    return NextResponse.json({ success: false, error: error.message }, { status: 500 })
  }
}
