// Widget Descriptions — info panel content for each widget
// Format: { source: 'veri kaynağı', purpose: 'amaç', interpret: 'yorumlama rehberi' }

export interface WidgetDescription { source: string; purpose: string; interpret: string }

const D = (source: string, purpose: string, interpret: string): WidgetDescription => ({ source, purpose, interpret })
const PMS = 'Elektra PMS rezervasyon verileri'
const PMS_FIN = 'Elektra PMS finansal verileri'
const OPS = 'Operasyon yönetim sistemi'
const HR = 'İnsan kaynakları sistemi'
const MKT = 'Pazarlama platformları'
const FNB = 'F&B yönetim sistemi'

export const WIDGET_DESCRIPTIONS: Record<string, WidgetDescription> = {
    // Existing 15
    'kpis': D(PMS, 'Toplam gelir, rez. sayısı ve ADR gibi temel KPI\'ları tek bakışta gösterir.', 'Yıllık trendlerle karşılaştırarak büyüme hızını izleyin; ADR düşerken gelir artıyorsa hacim odaklı büyüme var demektir.'),
    'monthly': D(PMS, 'Aylık gelir dağılımını grafik olarak izler.', 'Sezonsal dalgalanmaları tespit edin; düşük aylar için özel kampanya planlaması yapın.'),
    'channels': D(PMS, 'Rezervasyonların hangi kanallardan geldiğini gösterir.', 'Direkt rez. oranı yüksekse komisyon maliyetleri düşük demektir. OTA bağımlılığını %40 altında tutmayı hedefleyin.'),
    'roomTypes': D(PMS, 'Oda tiplerinin doluluk ve gelir katkısını analiz eder.', 'Düşük talep gören oda tiplerinde fiyat optimizasyonu veya upgrade stratejisi düşünün.'),
    'agencies': D(PMS, 'En çok üretim yapan acentaları sıralar.', 'İlk 5 acentanın toplam gelir içindeki payını izleyin; %50\'yi aşarsa bağımlılık riski var.'),
    'occupancy': D(PMS, 'Günlük ve dönemsel doluluk oranını izler.', '%85 üstü doluluk mükemmel; %60 altında kalırsa fiyat indirimi veya kampanya düşünün.'),
    'adr': D(PMS, 'Average Daily Rate — günlük ortalama oda fiyatı.', 'ADR yükselirken doluluk düşmüyorsa optimal fiyatlandırma yapılıyor demektir.'),
    'nationality': D(PMS, 'Misafir milliyetlerinin dağılımını gösterir.', 'Hakim pazarları ve büyüyen ülkeleri izleyin; pazarlama bütçesini buna göre dağıtın.'),
    'velocity': D(PMS, 'Rezervasyonların ne hızla geldiğini ölçer.', 'Hız düşüyorsa erken uyarı; kampanya veya fiyat ayarlaması gerekebilir.'),
    'lengthOfStay': D(PMS, 'Ortalama konaklama süresini gösterir.', 'LOS artışı daha az check-in/out operasyonu ve daha istikrarlı gelir demektir. Min Stay kısıtlamaları ile optimize edin.'),
    'revpar': D(PMS, 'Revenue Per Available Room — oda başı gelir.', 'RevPAR hem doluluk hem ADR\'yi yansıtır. Rakiplerle kıyaslayarak pazar konumunuzu değerlendirin.'),
    'budget': D(PMS_FIN, 'Bütçe hedefleri ile gerçekleşen geliri karşılaştırır.', 'Sapma oranı %5\'in altındaysa bütçe tutarlı demektir; üstündeyse revizyon gerekebilir.'),
    'callCenter': D(MKT, 'Çağrı merkezi performans metriklerini gösterir.', 'Dönüşüm oranı ve ortalama çağrı süresini izleyin; düşük dönüşüm eğitim ihtiyacını işaret eder.'),
    'forecast': D(PMS, 'Gelecek dönem doluluk ve gelir tahminini sunar.', 'Tahmin ile mevcut rez. arasındaki farkı kapatmak için proaktif satış stratejileri uygulayın.'),
    'operator': D(OPS, 'Operatörlerin performansını kıyaslar.', 'En verimli operatörleri ödüllendirin; düşük performansı eğitimle iyileştirin.'),

    // Revenue Charts
    'rev-daily-chart': D(PMS, 'Günlük gelir değişimini grafik olarak takip eder.', 'Ani düşüşler operasyonel sorunları, ani artışlar grup rez. veya etkinlikleri gösterir.'),
    'rev-weekly-chart': D(PMS, 'Haftalık gelir trendini izler.', 'Haftanın hangi günleri güçlü olduğunu belirleyip fiyat stratejinizi optimize edin.'),
    'rev-yoy-chart': D(PMS, 'Bu yıl ile geçen yılın gelirini kıyaslar.', 'YoY büyüme %10+ ise sağlıklı; negatifse acil aksiyon gerekir.'),
    'rev-roomtype-chart': D(PMS, 'Oda tiplerinin gelire katkısını gösterir.', 'En çok gelir getiren oda tipine yatırım yapın; düşük getirilileri yeniden konumlandırın.'),
    'rev-channel-chart': D(PMS, 'Kanalların gelir katkısını karşılaştırır.', 'Direkt kanal gelirini artırmak komisyon maliyetini düşürür.'),
    'rev-nationality-chart': D(PMS, 'Milliyete göre gelir dağılımını gösterir.', 'Yüksek harcama yapan milliyetlere odaklanın.'),
    'rev-segment-chart': D(PMS, 'İş segmentlerine göre gelir dağılımı.', 'Corporate vs Leisure dengesini izleyin.'),
    'rev-mealplan-chart': D(PMS, 'Pansiyon tiplerinin gelir katkısını gösterir.', 'AI ve FB pansiyonlar daha yüksek gelir sağlıyorsa teşvik edin.'),
    'rev-pace-chart': D(PMS, 'Gelir hızını geçen yılla karşılaştırır.', 'Pace geride kalıyorsa fiyat veya pazarlama aksiyonu alın.'),
    'rev-forecast-chart': D(PMS, 'Gelecek dönem gelir tahminini gösterir.', 'Tahmin ile hedef arasındaki boşluğu kapatmak için proaktif satış yapın.'),
    'rev-cumulative-chart': D(PMS, 'Kümülatif gelir birikimini izler.', 'Bütçe eğrisiyle karşılaştırarak geride mi önde mi olduğunuzu görün.'),
    'rev-hourly-chart': D(PMS, 'Saatlik gelir dağılımını gösterir.', 'Yoğun saatlerde kaynak planlaması yapın.'),
    'rev-tax-chart': D(PMS_FIN, 'KDV ve konaklama vergisi dağılımını gösterir.', 'Vergi yükünü izleyerek mali planlamayı optimize edin.'),
    'rev-commission-chart': D(PMS, 'Kanallara ödenen komisyonları analiz eder.', 'Yüksek komisyonlu kanallardan direkt kanala yönlendirme stratejisi geliştirin.'),
    'rev-refund-chart': D(PMS, 'İade ve iptallerin gelir etkisini gösterir.', 'İade oranı artıyorsa iptal politikasını gözden geçirin.'),
    // Revenue Data
    'rev-daily-kpi': D(PMS, 'Günlük gelir KPI\'larını özetler.', 'Hedefle karşılaştırarak günlük performansı değerlendirin.'),
    'rev-weekly-kpi': D(PMS, 'Haftalık gelir özetini sunar.', 'Haftalık trendleri izleyerek ayın sonunu tahmin edin.'),
    'rev-monthly-kpi': D(PMS, 'Aylık gelir detayını gösterir.', 'Bütçe ile sapma analizi yapın.'),
    'rev-quarterly-kpi': D(PMS, 'Çeyreklik gelir analizini sunar.', 'Mevsimsel kalıpları anlamak için çeyrekler arası kıyaslayın.'),
    'rev-upsell': D(PMS, 'Upsell gelirlerini takip eder.', 'Oda başı upsell gelirini artırmak için personel eğitimi verin.'),
    'rev-ancillary': D(PMS, 'Ek hizmet gelirlerini özetler.', 'Spa, minibar gibi ek gelirleri artırmak TRevPAR\'ı yükseltir.'),
    'rev-late-checkout': D(PMS, 'Geç çıkış gelirini izler.', 'Geç çıkış talebini fiyatlandırarak ek gelir oluşturun.'),
    'rev-early-checkin': D(PMS, 'Erken giriş gelirini izler.', 'Talep varsa otomatik teklif sistemi kurun.'),
    'rev-minibar': D(PMS, 'Minibar gelirlerini takip eder.', 'Oda başı minibar gelirini artırmak için ürün çeşitliliğini optimize edin.'),
    'rev-spa': D(PMS, 'Spa ve wellness gelirlerini gösterir.', 'Düşükse konaklama paketi ile entegre edin.'),
    'rev-laundry': D(PMS, 'Çamaşırhane gelirlerini izler.', 'Uzun konaklamalarda çamaşır paketi sunun.'),
    'rev-parking': D(PMS, 'Otopark gelirlerini takip eder.', 'Doluluk ile oranı karşılaştırın.'),
    'rev-transfer': D(PMS, 'Havalimanı transfer gelirlerini gösterir.', 'Rez. aşamasında otomatik teklif dönüşümü artırır.'),
    'rev-meeting-room': D(PMS, 'Toplantı salonu gelirlerini izler.', 'Kapasite kullanımı düşükse corporate pazarlamayı artırın.'),
    'rev-deposit': D(PMS, 'Depozito tahsilat durumunu gösterir.', 'Tahsil edilmemiş depozitolar nakit akış riski oluşturur.'),
    // Revenue Graphs
    'rev-heatmap': D(PMS, 'Gelir yoğunluğunu ısı haritasıyla gösterir.', 'Kırmızı bölgeler düşük geliri, yeşil bölgeler güçlü günleri gösterir.'),
    'rev-treemap': D(PMS, 'Gelir kaynaklarını ağaç haritasıyla görselleştirir.', 'Büyük kutular en büyük gelir kaynağını gösterir.'),
    'rev-waterfall': D(PMS, 'Gelire katkıda bulunan artış ve azalışları şelale formatında gösterir.', 'Her adımın gelire pozitif mi negatif mi etki ettiğini izleyin.'),
    'rev-scatter': D(PMS, 'Fiyat ve doluluk ilişkisini scatter ile gösterir.', 'Optimal fiyat noktasını bulmak için kümelenmeyi inceleyin.'),
    'rev-gauge': D(PMS_FIN, 'Bütçe gerçekleşme oranını göstergede gösterir.', '%90+ mükemmel, %80-90 iyi, %80 altı aksiyon gerektirir.'),
    'rev-sparklines': D(PMS, 'Temel gelir metriklerinin mini trendlerini gösterir.', 'Hızlı bakışla hangi metriklerin yükseldiğini görün.'),
    'rev-funnel': D(PMS, 'Rez\'dan gelire dönüşüm hunisini gösterir.', 'Her aşamadaki kayıp oranını düşürmeye odaklanın.'),
    'rev-comparison-radar': D(PMS, 'Gelir metriklerini radar grafiğiyle karşılaştırır.', 'Zayıf alanları tespit edip önceliklendirin.'),

    // Occupancy Charts
    'occ-daily-chart': D(PMS, 'Günlük doluluk trendini izler.', 'Düşük günler için son dakika kampanyaları planlayın.'),
    'occ-monthly-chart': D(PMS, 'Aylık doluluk trendini gösterir.', 'Mevsimsel kalıpları anlamak için geçen yılla kıyaslayın.'),
    'occ-weekday-chart': D(PMS, 'Haftanın günlerine göre doluluk dağılımı.', 'Hafta içi düşükse corporate segment veya özel fiyat düşünün.'),
    'occ-roomtype-chart': D(PMS, 'Oda tiplerinin doluluk performansını gösterir.', 'Düşük doluluk oda tiplerinde fiyat/upgrade stratejisi geliştirin.'),
    'occ-floor-chart': D(PMS, 'Kat bazlı doluluk dağılımını gösterir.', 'Düşük doluluklu katlarda bakım planlaması yapılabilir.'),
    'occ-forecast-chart': D(PMS, '14 günlük doluluk tahminini sunar.', 'Düşük tahmin günleri için proaktif satış yapın.'),
    'occ-yoy-chart': D(PMS, 'Doluluk oranını geçen yılla karşılaştırır.', 'YoY düşüş varsa pazar koşullarını ve rekabeti analiz edin.'),
    'occ-ooo-chart': D(OPS, 'Servis dışı (Out of Order) oda sayısını izler.', 'OOO oranını %3 altında tutmayı hedefleyin.'),
    'occ-upgrade-chart': D(PMS, 'Oda upgrade verilerini analiz eder.', 'Upgrade oranı gelir optimizasyonunu gösterir.'),
    'occ-status-chart': D(PMS, 'Oda durumlarının dağılımını gösterir.', 'Temiz/kirli/arıza oranlarını izleyerek operasyonel verimliliği ölçün.'),
    'occ-category-mix': D(PMS, 'Oda kategorilerinin dağılımını gösterir.', 'Talep yüksek kategorilere odaklanın.'),
    'occ-rate-analysis': D(PMS, 'Oda fiyat performansını analiz eder.', 'Farklı fiyat seviyelerinin doluluk etkisini değerlendirin.'),
    // Occupancy Data
    'occ-today-status': D(PMS, 'Bugünkü oda durumunu özetler.', 'Giriş/çıkış dengesini izleyin.'),
    'occ-arrivals-today': D(PMS, 'Bugünkü giriş yapacak misafirleri listeler.', 'VIP ve özel isteklere hazırlıklı olun.'),
    'occ-departures-today': D(PMS, 'Bugünkü çıkış yapacak misafirleri listeler.', 'Geç çıkış taleplerini proaktif yönetin.'),
    'occ-stayovers': D(PMS, 'Devam eden konaklamaları gösterir.', 'Stayover misafirlere mid-stay memnuniyet kontrolü yapın.'),
    'occ-no-shows': D(PMS, 'Gelmeme (no-show) vakalarını raporlar.', 'No-show oranı yüksekse garanti politikasını sıkılaştırın.'),
    'occ-walkins': D(PMS, 'Rezervasyonsuz gelen misafirleri izler.', 'Walk-in oranı yüksekse fiyatlandırmayı optimize edin.'),
    'occ-vip-rooms': D(PMS, 'VIP misafirlere atanan odaları gösterir.', 'VIP odalarının en iyi durumda olduğundan emin olun.'),
    'occ-connecting': D(PMS, 'Bağlantılı oda kullanımını takip eder.', 'Aile segmentinin talebini anlamak için izleyin.'),
    'occ-housekeeping': D(OPS, 'Housekeeping oda durumlarını gösterir.', 'Temizlenmemiş oda sayısını check-in saatinden önce sıfırlayın.'),
    'occ-maintenance': D(OPS, 'Bakım ve arıza kayıtlarını listeler.', 'Tekrarlayan arızaları tespit ederek kalıcı çözüm üretin.'),
    'occ-inhouse-list': D(PMS, 'Otelde bulunan misafir listesini gösterir.', 'Toplam misafir ve oda sayısını doğrulayın.'),
    'occ-early-late': D(PMS, 'Erken giriş ve geç çıkış istatistiklerini gösterir.', 'Talep yüksekse ücretli hizmet olarak sunun.'),
    // Occupancy Graphs
    'occ-heatmap': D(PMS, 'Doluluk yoğunluğunu ısı haritasıyla gösterir.', 'Koyu renkli hücreler yüksek doluluk günlerini gösterir.'),
    'occ-floor-map': D(PMS, 'Kat planı üzerinde doluluk durumunu görselleştirir.', 'Boş odaları ve doluluğu bir bakışta görün.'),
    'occ-bubble': D(PMS, 'Oda tip/fiyat/doluluk ilişkisini balon grafiğiyle gösterir.', 'Büyük balonlar yüksek gelir potansiyelini gösterir.'),
    'occ-gauge': D(PMS, 'Anlık doluluk oranını göstergede gösterir.', '%85+ mükemmel, %60 altı aksiyon gerektirir.'),
    'occ-timeline': D(PMS, 'Oda dolulukunu zaman çizelgesinde gösterir.', 'Boşluklar satış fırsatlarını temsil eder.'),

    // Guest & CRM
    'guest-nationality-pie': D(PMS, 'Milliyet dağılımını pasta grafiğiyle gösterir.', 'Hakim pazarlara yönelik dil ve kültür uyumunu sağlayın.'),
    'guest-repeat-chart': D(PMS, 'Tekrar gelen misafir trendini izler.', 'Tekrar oranı %30+ ise sadakat programı etkili demektir.'),
    'guest-satisfaction-chart': D(PMS, 'Misafir memnuniyet puanı trendini gösterir.', 'Düşüş trendi varsa hizmet kalitesini acil inceleyin.'),
    'guest-demographics-chart': D(PMS, 'Yaş ve cinsiyet dağılımını analiz eder.', 'Hedef kitleye uygun hizmet ve pazarlama stratejisi geliştirin.'),
    'guest-spending-chart': D(PMS, 'Misafir harcama kalıplarını gösterir.', 'Yüksek harcama yapan segmentlere özel paketler sunun.'),
    'guest-los-chart': D(PMS, 'Konaklama süresi dağılımını gösterir.', 'Uzun konaklama segmentini büyütmek istikrar sağlar.'),
    'guest-source-chart': D(PMS, 'Misafir kaynak kanallarını analiz eder.', 'En verimli kanalları belirleyin.'),
    'guest-loyalty-chart': D(PMS, 'Sadakat programı istatistiklerini gösterir.', 'Üye dönüşüm oranını artırmaya odaklanın.'),
    'guest-complaint-chart': D(PMS, 'Şikayet kategorilerini gösterir.', 'En sık şikayet konusuna öncelik verin.'),
    'guest-review-chart': D(MKT, 'Online yorum trendini izler.', 'Puan düşüşüne hızlı müdahale edin.'),
    'guest-vip-list': D(PMS, 'VIP misafir listesini gösterir.', 'VIP\'lere özel karşılama ve hizmet hazırlığı yapın.'),
    'guest-repeat-list': D(PMS, 'Tekrar gelen misafirleri listeler.', 'Kişiselleştirilmiş deneyim sunarak sadakati güçlendirin.'),
    'guest-birthday': D(PMS, 'Yaklaşan doğum günlerini gösterir.', 'Sürpriz jestler misafir memnuniyetini artırır.'),
    'guest-anniversary': D(PMS, 'Yıl dönümü raporunu gösterir.', 'Özel günlerde kişisel dokunuş yapın.'),
    'guest-special-req': D(PMS, 'Özel istekleri analiz eder.', 'Sık tekrarlanan istekleri standart hale getirin.'),
    'guest-allergy': D(PMS, 'Alerji ve diyet bilgilerini raporlar.', 'F&B ekibini bilgilendirerek risk ortadan kaldırın.'),
    'guest-blacklist': D(PMS, 'Kara listeyi gösterir.', 'Rez. kabul öncesi kontrol edin.'),
    'guest-feedback-summary': D(PMS, 'Geri bildirim özetini gösterir.', 'Tematik analiz yaparak iyileştirme fırsatlarını belirleyin.'),
    'guest-top-spenders': D(PMS, 'En çok harcayan misafirleri sıralar.', 'Bu misafirlere özel VIP programı uygulayın.'),
    'guest-country-revenue': D(PMS, 'Ülke bazlı gelir dağılımını gösterir.', 'Yüksek getirili ülkelere pazarlama bütçesi artırın.'),
    'guest-preferences': D(PMS, 'Misafir tercihlerini analiz eder.', 'Kişiselleştirilmiş hizmet sunun.'),
    'guest-communication': D(PMS, 'İletişim kayıtlarını gösterir.', 'İletişim sıklığını ve kanallarını optimize edin.'),
    'guest-world-map': D(PMS, 'Misafir dağılımını dünya haritasında gösterir.', 'Potansiyel yeni pazarları keşfedin.'),
    'guest-satisfaction-radar': D(PMS, 'Memnuniyet boyutlarını radar grafiğiyle gösterir.', 'Zayıf eksenleri iyileştirme önceliği yapın.'),
    'guest-journey-sankey': D(PMS, 'Misafir yolculuğunu Sankey ile görselleştirir.', 'Kayıp noktalarını tespit edin.'),
    'guest-segmentation-bubble': D(PMS, 'Misafir segmentlerini balon grafiğiyle gösterir.', 'Büyük balonlar hedef segmentleri gösterir.'),
    'guest-retention-funnel': D(PMS, 'Misafir tutma hunisini gösterir.', 'Her aşamadaki kayıp oranını düşürün.'),

    // Reservation & Sales
    'res-pace-chart': D(PMS, 'Booking pace\'i geçen yılla kıyaslar.', 'Geride kalma erken uyarıdır; kampanya düşünün.'),
    'res-leadtime-chart': D(PMS, 'Rez. ne kadar önceden yapıldığını analiz eder.', 'Lead time kısalıyorsa son dakika talebi artıyor demektir.'),
    'res-cancel-chart': D(PMS, 'İptal oranı trendini izler.', '%20 üstü iptal oranı politika revizyonu gerektirir.'),
    'res-noshow-chart': D(PMS, 'No-show trendini izler.', 'Garanti politikası ile no-show oranını düşürün.'),
    'res-channel-trend': D(PMS, 'Kanal bazlı rez. trendini gösterir.', 'Direkt kanalı büyütmeyi hedefleyin.'),
    'res-daily-pickup': D(PMS, 'Günlük pick-up hızını ölçer.', 'Pick-up yavaşlıyorsa fiyat ayarlaması yapın.'),
    'res-rate-code': D(PMS, 'Rate code performansını analiz eder.', 'Düşük performanslı rate code\'ları kapatın.'),
    'res-promo-chart': D(PMS, 'Promosyon kodlarının etkisini ölçer.', 'ROI\'si düşük promosyonları sonlandırın.'),
    'res-group-chart': D(PMS, 'Grup rez. özetini sunar.', 'Grup rez. payını toplam gelirin %20-30\'unda tutun.'),
    'res-overbooking': D(PMS, 'Overbooking durumunu analiz eder.', 'Overbooking oranını no-show oranına göre ayarlayın.'),
    'res-modification': D(PMS, 'Rez. değişiklik trendini izler.', 'Sık değişiklik esnek politika talebi gösterir.'),
    'res-board-mix': D(PMS, 'Pansiyon tipi dağılımını gösterir.', 'AI payı yüksekse F&B geliri dahil değerlendirin.'),
    'res-today-arrivals': D(PMS, 'Bugünkü girişleri detaylı listeler.', 'VIP ve özel isteklere dikkat edin.'),
    'res-today-departures': D(PMS, 'Bugünkü çıkışları detaylı listeler.', 'Açık hesapları kapatmayı unutmayın.'),
    'res-pending': D(PMS, 'Onay bekleyen rez. listeler.', 'Bekleme süresini kısaltarak kayıp oranını düşürün.'),
    'res-confirmed': D(PMS, 'Onaylı rez. listeler.', 'Onaylı rez. sayısını hedefle karşılaştırın.'),
    'res-cancelled-list': D(PMS, 'İptal edilen rez. listeler.', 'İptal nedenlerini analiz edin.'),
    'res-waitlist': D(PMS, 'Bekleme listesini gösterir.', 'İptal durumunda hızlı dönüş yapın.'),
    'res-allotment': D(PMS, 'Acenta allotment kullanımını gösterir.', 'Düşük kullanım allotment revizyonu gerektirir.'),
    'res-agency-prod': D(PMS, 'Acenta üretim raporunu sunar.', 'Üretimi düşen acentalarla iletişime geçin.'),
    'res-source-mix': D(PMS, 'Kaynak mix tablosunu gösterir.', 'Kanal çeşitliliğini koruyun.'),
    'res-avg-rate': D(PMS, 'Ortalama fiyat raporunu sunar.', 'ADR düşüyorsa fiyat erozyonunu önleyin.'),
    'res-revenue-by-stay': D(PMS, 'Konaklama süresine göre gelir dağılımı.', 'Uzun konaklama gelir payını artırın.'),
    'res-night-audit': D(PMS, 'Night audit özetini gösterir.', 'Farkları ve uyumsuzlukları kontrol edin.'),
    'res-pace-waterfall': D(PMS, 'Booking pace\'i şelale grafiğiyle gösterir.', 'Kırılım noktalarını belirleyin.'),
    'res-channel-sankey': D(PMS, 'Kanal akışını Sankey ile gösterir.', 'Kanal geçişlerini ve dönüşümleri izleyin.'),
    'res-heatmap': D(PMS, 'Rez. yoğunluğunu ısı haritasıyla gösterir.', 'Yoğun dönemlerde fiyat artışı uygulayın.'),
    'res-funnel': D(PMS, 'Rez. hunisini gösterir.', 'Hangi aşamada kayıp olduğunu tespit edin.'),
    'res-calendar': D(PMS, 'Rez. takvimini görselleştirir.', 'Boş günleri tespit edip satış yapın.'),
    'res-comparison-bar': D(PMS, 'Sezon karşılaştırmaını bar grafiğiyle gösterir.', 'Dönemler arası performans farkını izleyin.'),

    // Operations
    'ops-checkin-volume': D(OPS, 'Saatlik check-in hacmini gösterir.', 'Yoğun saatlerde ek personel planlayın.'),
    'ops-checkout-volume': D(OPS, 'Saatlik check-out hacmini gösterir.', 'Yoğun saatlerde express check-out teşvik edin.'),
    'ops-housekeeping-chart': D(OPS, 'HK temizlik performansını izler.', 'Oda başı temizlik süresini optimize edin.'),
    'ops-maintenance-chart': D(OPS, 'Arıza kategorilerini gösterir.', 'Tekrarlayan kategorilerde önleyici bakım yapın.'),
    'ops-request-chart': D(OPS, 'Misafir istek trendini izler.', 'Sık istekleri proaktif karşılayın.'),
    'ops-response-time': D(OPS, 'Yanıt süresi analizi.', 'Hedef: 15dk altında yanıt oranı %90+.'),
    'ops-energy-chart': D(OPS, 'Enerji tüketimini izler.', 'Dolulukla normalize ederek verimliliği ölçün.'),
    'ops-water-chart': D(OPS, 'Su tüketimini takip eder.', 'Oda başı su kullanımını düşürmeyi hedefleyin.'),
    'ops-complaint-trend': D(OPS, 'Şikayet trendini gösterir.', 'Düşüş trendi olumlu; artış acil müdahale gerektirir.'),
    'ops-task-completion': D(OPS, 'Görev tamamlama oranını gösterir.', '%95+ hedefleyin.'),
    'ops-mod-report': D(OPS, 'Manager on Duty raporunu sunar.', 'Kritik olayları ve aksiyonları takip edin.'),
    'ops-night-audit-data': D(OPS, 'Night audit detaylarını gösterir.', 'Farkları ve uyumsuzlukları çözümleyin.'),
    'ops-lost-found': D(OPS, 'Kayıp ve bulunmuş eşya kayıtları.', 'İade süresini kısaltarak misafir memnuniyetini artırın.'),
    'ops-security-log': D(OPS, 'Güvenlik olaylarını loglar.', 'Tekrarlayan güvenlik sorunlarına kalıcı çözüm üretin.'),
    'ops-incident': D(OPS, 'Olay raporlarını gösterir.', 'Her olayı kök neden analizi ile inceleyin.'),
    'ops-pool-status': D(OPS, 'Havuz ve plaj durumunu gösterir.', 'Kapasite yönetimini optimize edin.'),
    'ops-parking': D(OPS, 'Otopark doluluk durumunu gösterir.', 'Yoğun dönemlerde valet hizmeti planlayın.'),
    'ops-laundry-stats': D(OPS, 'Çamaşırhane istatistiklerini sunar.', 'Parça başı maliyet ve süreyi izleyin.'),
    'ops-minibar-track': D(OPS, 'Minibar takibini gösterir.', 'Tüketim oranı düşükse ürün çeşitliliğini değiştirin.'),
    'ops-shuttle-schedule': D(OPS, 'Transfer programını gösterir.', 'Doluluk ile koordine edin.'),
    'ops-amenity-usage': D(OPS, 'Tesis kullanım istatistiklerini gösterir.', 'Düşük kullanımlı tesisleri değerlendirin.'),
    'ops-key-card': D(OPS, 'Kart basım istatistiklerini gösterir.', 'Yüksek yeniden basım stok ve arıza işaretçisi olabilir.'),
    'ops-floor-heatmap': D(OPS, 'Kat bazlı ısı haritası.', 'Yoğun katlarda ek kaynak planlayın.'),
    'ops-timeline': D(OPS, 'Operasyon olaylarını zaman çizelgesinde gösterir.', 'Darboğazları tespit edin.'),
    'ops-response-gauge': D(OPS, 'Yanıt süresi göstergesi.', 'Yeşil bölge: hedef içinde; kırmızı: iyileştirme gerekli.'),
    'ops-energy-gauge': D(OPS, 'Enerji tüketim göstergesi.', 'Bütçe ile karşılaştırın.'),
    'ops-task-kanban': D(OPS, 'Görevleri Kanban panosunda gösterir.', 'Bekleyen görev sayısını minimum tutun.'),

    // F&B
    'fnb-restaurant-rev': D(FNB, 'Restoran gelirini izler.', 'Cover başı geliri artırmaya odaklanın.'),
    'fnb-bar-rev': D(FNB, 'Bar gelirini izler.', 'Happy hour ve özel etkinliklerle geliri artırın.'),
    'fnb-roomservice-chart': D(FNB, 'Oda servisi trendini gösterir.', 'Talep saatlerini belirleyin.'),
    'fnb-breakfast-count': D(FNB, 'Kahvaltı katılımını sayar.', 'Doluluk ile kıyaslayarak capture rate ölçün.'),
    'fnb-allinc-consumption': D(FNB, 'All-inclusive tüketim analizini gösterir.', 'Kişi başı maliyeti kontrol edin.'),
    'fnb-menu-popularity': D(FNB, 'Menü popülerliğini analiz eder.', 'Az sipariş edilen kalemleri menüden çıkarmayı düşünün.'),
    'fnb-food-cost': D(FNB, 'Gıda maliyet oranını gösterir.', 'Hedef: %28-32 arası. Üstündeyse reçete revizyonu yapın.'),
    'fnb-beverage-cost': D(FNB, 'İçecek maliyet oranını gösterir.', 'Hedef: %18-25 arası.'),
    'fnb-cover-count': D(FNB, 'Cover sayısı trendini izler.', 'Düşüş trendi menü veya atmosfer değişikliği sinyali.'),
    'fnb-avg-check': D(FNB, 'Ortalama hesap tutarını gösterir.', 'Upselling eğitimi ile artırın.'),
    'fnb-daily-summary': D(FNB, 'F&B günlük özetini sunar.', 'Bütçe ile kıyaslayın.'),
    'fnb-waste-report': D(FNB, 'İsraf miktarını raporlar.', 'İsraf oranını %2 altında tutmayı hedefleyin.'),
    'fnb-stock-alert': D(FNB, 'Düşük stok uyarılarını gösterir.', 'Kritik kalemleri acil tedarik edin.'),
    'fnb-recipe-cost': D(FNB, 'Reçete maliyetlerini analiz eder.', 'Pahalı reçetelerde alternatif malzeme araştırın.'),
    'fnb-supplier-perf': D(FNB, 'Tedarikçi performansını değerlendirir.', 'Düşük puanlı tedarikçileri değiştirmeyi düşünün.'),
    'fnb-special-diet': D(FNB, 'Özel diyet taleplerini raporlar.', 'Talep artıyorsa menüyü genişletin.'),
    'fnb-banquet-rev': D(FNB, 'Ziyafet ve etkinlik gelirlerini gösterir.', 'Kapasite kullanımını artırın.'),
    'fnb-outlet-compare': D(FNB, 'Outlet performanslarını karşılaştırır.', 'Düşük performanslı outlet için aksiyon planı yapın.'),
    'fnb-happy-hour': D(FNB, 'Happy hour performansını gösterir.', 'ROI pozitifse saatleri genişletmeyi düşünün.'),
    'fnb-inventory': D(FNB, 'F&B envanter durumunu gösterir.', 'Stok devir hızını optimize edin.'),
    'fnb-treemap': D(FNB, 'F&B gelir ağaç haritasını gösterir.', 'Büyük kutular en büyük gelir kaynaklarıdır.'),
    'fnb-cost-gauge': D(FNB, 'Maliyet oranı göstergesi.', 'Yeşil: hedef içinde; kırmızı: maliyet çok yüksek.'),
    'fnb-popularity-bubble': D(FNB, 'Menü popülerliğini balon grafiğiyle gösterir.', 'Büyük balonlar en popüler kalemleri gösterir.'),
    'fnb-outlet-radar': D(FNB, 'Outlet performansını radar ile gösterir.', 'Zayıf eksenler iyileştirme fırsatıdır.'),
    'fnb-flow-sankey': D(FNB, 'F&B gelir akışını Sankey ile gösterir.', 'Gelir dağılımını kanallar arası izleyin.'),

    // Marketing
    'mkt-direct-vs-ota': D(MKT, 'Direkt ve OTA rez. oranını karşılaştırır.', 'Direkt oranı %40+ hedefleyin. Komisyon tasarrufu sağlar.'),
    'mkt-website-conversion': D(MKT, 'Website dönüşüm oranını gösterir.', '%3+ dönüşüm oranı sektör ortalaması üstüdür.'),
    'mkt-email-campaign': D(MKT, 'E-posta kampanya metriklerini gösterir.', 'Açılma oranı %20+, tıklama %3+ hedefleyin.'),
    'mkt-social-engagement': D(MKT, 'Sosyal medya etkileşimlerini izler.', 'Etkileşim oranı artan platformlara yatırım artırın.'),
    'mkt-seo-ranking': D(MKT, 'SEO sıralama performansını gösterir.', 'İlk sayfa sıralaması organik trafik sağlar.'),
    'mkt-ppc-roi': D(MKT, 'PPC reklam ROI\'sini gösterir.', 'ROAS 3x+ ise kampanya kârlıdır.'),
    'mkt-review-scores': D(MKT, 'Online yorum puanlarını izler.', 'Düşüş trendi acil müdahale gerektirir.'),
    'mkt-competitor-rate': D(MKT, 'Rakip fiyatlarıyla karşılaştırır.', 'Fiyat pozisyonunuzu pazar konumuna göre ayarlayın.'),
    'mkt-market-share': D(MKT, 'Bölgesel pazar payını gösterir.', 'Pazar payı artışı sağlıklı büyüme göstergesidir.'),
    'mkt-brand-awareness': D(MKT, 'Marka bilinirlik ölçümünü gösterir.', 'Bilinirlik artışı uzun vadeli talep yaratır.'),
    'mkt-campaign-summary': D(MKT, 'Kampanya özetini gösterir.', 'Aktif kampanya ROI\'sini izleyin.'),
    'mkt-promo-redemption': D(MKT, 'Promosyon kullanım oranını gösterir.', 'Kullanım oranı düşükse dağıtım kanalını değiştirin.'),
    'mkt-referral': D(MKT, 'Referans kaynak analizini gösterir.', 'En verimli referans kanallarına odaklanın.'),
    'mkt-review-list': D(MKT, 'Son yorumları listeler.', 'Olumsuz yorumlara hızlı yanıt verin.'),
    'mkt-meta-perf': D(MKT, 'Meta search performansını gösterir.', 'Meta arama trafik payını izleyin.'),
    'mkt-ota-ranking': D(MKT, 'OTA sıralama durumunu gösterir.', 'İlk 10\'da olmak görünürlüğü artırır.'),
    'mkt-loyalty-stats': D(MKT, 'Sadakat programı KPI\'larını gösterir.', 'Aktif üye oranını artırmaya odaklanın.'),
    'mkt-newsletter': D(MKT, 'Newsletter istatistiklerini gösterir.', 'Abone büyüme trendini izleyin.'),
    'mkt-influencer': D(MKT, 'Influencer işbirliği detaylarını gösterir.', 'ROI\'si yüksek influencer\'larla devam edin.'),
    'mkt-content-perf': D(MKT, 'İçerik performansını analiz eder.', 'Yüksek etkileşimli formatları çoğaltın.'),
    'mkt-channel-funnel': D(MKT, 'Kanal hunisini gösterir.', 'Her aşamadaki kayıp oranını düşürün.'),
    'mkt-attribution': D(MKT, 'Atıf modelini Sankey ile gösterir.', 'Dönüşüme en çok katkı yapan kanalları belirleyin.'),
    'mkt-competitor-radar': D(MKT, 'Rakip karşılaştırmasını radar ile gösterir.', 'Zayıf noktalarınızı güçlendirin.'),
    'mkt-roi-scatter': D(MKT, 'Kampanya ROI\'sini scatter ile gösterir.', 'Yüksek ROI kampanyalarına bütçe artırın.'),
    'mkt-journey-flow': D(MKT, 'Misafir yolculuğunu görselleştirir.', 'Dönüşüm darboğazlarını tespit edin.'),

    // Staff & HR
    'staff-schedule-chart': D(HR, 'Vardiya dağılımını gösterir.', 'Dengeli dağılım iş yükünü eşitler.'),
    'staff-overtime-chart': D(HR, 'Fazla mesai saatlerini izler.', 'Yüksek fazla mesai personel eksikliği işaretidir.'),
    'staff-labor-cost': D(HR, 'İşçilik maliyetini gelirle oranlar.', 'Hedef: gelirin %22-28\'i. Üstünde verimlilik sorunu var.'),
    'staff-productivity': D(HR, 'Verimlilik analizini gösterir.', 'Oda başı personel verimliliğini izleyin.'),
    'staff-turnover': D(HR, 'Personel devir oranını gösterir.', '%10 altı sağlıklı; üstünde elde tutma stratejisi gerekir.'),
    'staff-training': D(HR, 'Eğitim tamamlama oranını gösterir.', '%100 tamamlama hedefleyin.'),
    'staff-attendance': D(HR, 'Devam durumunu özetler.', 'Devamsızlık oranını %3 altında tutun.'),
    'staff-department': D(HR, 'Departman dağılımını gösterir.', 'FTE/oda oranını sektör ortalaması ile karşılaştırın.'),
    'staff-roster': D(HR, 'Günlük kadro listesini gösterir.', 'Kritik pozisyon boşluklarını kontrol edin.'),
    'staff-leave': D(HR, 'İzin takibini gösterir.', 'Yoğun dönemlerde izin kısıtlaması uygulayın.'),
    'staff-performance': D(HR, 'Performans değerlendirmelerini özetler.', 'Düşük performans eğitim planı gerektirir.'),
    'staff-certification': D(HR, 'Sertifika durumunu gösterir.', 'Süresi dolan sertifikaları yeniletin.'),
    'staff-onboarding': D(HR, 'İşe alım süreçlerini izler.', 'Onboarding süresini optimize edin.'),
    'staff-payroll-summary': D(HR, 'Maaş bordro özetini gösterir.', 'Bütçe ile sapma analizi yapın.'),
    'staff-tip-report': D(HR, 'Bahşiş dağılımını raporlar.', 'Adil dağılım personel memnuniyetini artırır.'),
    'staff-uniform': D(HR, 'Üniforma takibini gösterir.', 'Stok durumunu izleyin.'),
    'staff-org-chart': D(HR, 'Organizasyon şemasını gösterir.', 'Raporlama yapısını net tutun.'),
    'staff-workload-heatmap': D(HR, 'İş yükü dağılımını ısı haritasıyla gösterir.', 'Kırmızı bölgelerde ek kaynak gerekir.'),
    'staff-satisfaction-gauge': D(HR, 'Personel memnuniyet göstergesi.', '%80+ hedefleyin. Düşükse anket detaylarını inceleyin.'),
    'staff-cost-pie': D(HR, 'İşçilik maliyet dağılımını gösterir.', 'SGK ve prim paylarını optimize edin.'),

    // Yield Management
    'yield-rate-strategy': D(PMS, 'Fiyat strateji performansını gösterir.', 'Hedef ADR ile gerçekleşeni karşılaştırın.'),
    'yield-demand-forecast': D(PMS, 'Talep tahminini gösterir.', 'Düşük talep günlerinde özel fiyat uygulayın.'),
    'yield-compset': D(PMS, 'CompSet fiyat karşılaştırmasını gösterir.', 'Rakiplere göre konumunuzu değerlendirin.'),
    'yield-pickup': D(PMS, 'Pick-up hızını gösterir.', 'Hızlı pick-up fiyat artırma fırsatıdır.'),
    'yield-displacement': D(PMS, 'Displacement analizini gösterir.', 'Düşük fiyatlı rez.\'ın yüksek fiyatlıyı engellemesini ölçün.'),
    'yield-los-pattern': D(PMS, 'LOS kalıbını gösterir.', 'Min Stay kısıtlamalarını LOS verisine göre ayarlayın.'),
    'yield-dow-analysis': D(PMS, 'Gün bazlı performans analizi.', 'Güçlü günlerde fiyat artırın; zayıf günlerde kampanya yapın.'),
    'yield-seasonal': D(PMS, 'Sezonsal trendleri gösterir.', 'Sezon geçişlerinde fiyat stratejinizi güncelleyin.'),
    'yield-rate-shop': D(PMS, 'Rate shopping tablosunu sunar.', 'Oda tipi bazlı fiyat optimizasyonu yapın.'),
    'yield-restrictions': D(PMS, 'Aktif kısıtlamaları listeler.', 'Gereksiz kısıtlamaları kaldırarak satışı açın.'),
    'yield-overrides': D(PMS, 'Manuel fiyat override\'ları gösterir.', 'Override sayısı azsa sistem otomasyonu iyi çalışıyor demektir.'),
    'yield-segment-mix': D(PMS, 'Segment mix dağılımını gösterir.', 'Yüksek getirili segmentlerin payını artırın.'),
    'yield-channel-margin': D(PMS, 'Kanal bazlı kar marjını gösterir.', 'Düşük marjlı kanallardan yüksek marjlıya yönlendirin.'),
    'yield-dynamic-pricing': D(PMS, 'Dinamik fiyatlama loglarını gösterir.', 'Otomasyon kararlarını doğrulayın.'),
    'yield-benchmark': D(PMS, 'Benchmark KPI\'larını gösterir.', 'Sektör ortalaması ile karşılaştırarak pozisyonunuzu belirleyin.'),
    'yield-price-elasticity': D(PMS, 'Fiyat esneklik grafiğini gösterir.', '-1\'den düşükse elastik talep; fiyat değişimleri talebi çok etkiler.'),
    'yield-demand-heatmap': D(PMS, 'Talep yoğunluğunu ısı haritasıyla gösterir.', 'Yoğun hücrelerde ek kapasite/fiyat artışı düşünün.'),
    'yield-optimal-rate': D(PMS, 'Bugün için optimal fiyat önerisini gösterir.', 'Algoritmik öneriyi pazar koşullarıyla doğrulayın.'),
    'yield-revenue-gauge': D(PMS, 'Gelir potansiyel göstergesini gösterir.', 'Potansiyelin %90+\'ını yakalamayı hedefleyin.'),

    // Financial
    'fin-pnl-chart': D(PMS_FIN, 'Kâr-zarar trendini gösterir.', 'Gelir/gider dengesini izleyin; marj düşüyorsa giderleri inceleyin.'),
    'fin-cashflow-chart': D(PMS_FIN, 'Nakit akış durumunu gösterir.', 'Tahsilat oranı %90+ olmalı.'),
    'fin-ar-aging': D(PMS_FIN, 'Alacak yaşlandırma raporunu gösterir.', '90+ gün alacaklar risk oluşturur; tahsilat hızlandırın.'),
    'fin-ap-aging': D(PMS_FIN, 'Borç yaşlandırma raporunu gösterir.', 'Vade sürelerine uyarak kredi itibarını koruyun.'),
    'fin-expense-chart': D(PMS_FIN, 'Gider kategori trendini gösterir.', 'En büyük gider kalemlerini optimize edin.'),
    'fin-payment-method': D(PMS_FIN, 'Ödeme yöntemlerinin dağılımını gösterir.', 'Kredi kartı komsiyon maliyetini izleyin.'),
    'fin-tax-summary': D(PMS_FIN, 'Vergi özetini gösterir.', 'Vergi yükümlülüklerini zamanında karşılayın.'),
    'fin-budget-gauge': D(PMS_FIN, 'Bütçe gerçekleşme oranını gösterir.', '%90+ hedefleyin.'),
    'fin-cost-breakdown': D(PMS_FIN, 'Maliyet kırılımını treemap ile gösterir.', 'Büyük alanlar en büyük gider kalemleridir.'),
    'fin-ratio-radar': D(PMS_FIN, 'Finansal oranları radar ile gösterir.', 'Zayıf oranları iyileştirme önceliği yapın.'),
}
